import type { Violation } from "@/validation/violation"

export const exampleViolations: Violation[] = [
  {
    id: "v-2024-001",
    studentId: "2023-45678",
    studentName: "John Dela Cruz",
    violations: "Lost Key",
    violationType: "lost_key",
    dateOfInspection: Date.now() - 1000 * 60 * 60 * 24 * 7,
    dateReported: Date.now() - 1000 * 60 * 60 * 24 * 6,
    totalFine: 250,
    amountPaid: 250,
    fineStatus: "paid",
    lockerId: "L-A101",
    description: "Student reported losing locker key and requested replacement",
    reportedBy: "Michelle Santos",
    evidence: ["img-lost-key-001.jpg"],
    resolutionNotes: "Key replaced and fine paid in full on May 20, 2024",
  },
  {
    id: "v-2024-002",
    studentId: "2023-56789",
    studentName: "Maria Garcia",
    violations: "Damaged Locker",
    violationType: "damaged_locker",
    dateOfInspection: Date.now() - 1000 * 60 * 60 * 24 * 3,
    dateReported: Date.now() - 1000 * 60 * 60 * 24 * 3,
    totalFine: 500,
    amountPaid: 0,
    fineStatus: "unpaid",
    lockerId: "L-B205",
    description: "Door hinge broken due to misuse, requires repair",
    reportedBy: "Robert Tan",
    evidence: ["img-damage-001.jpg", "img-damage-002.jpg"],
  },
  {
    id: "v-2024-003",
    studentId: "2023-67890",
    studentName: "James Reyes",
    violations: "Unauthorized Use",
    violationType: "unauthorized_use",
    dateOfInspection: Date.now() - 1000 * 60 * 60 * 24 * 10,
    dateReported: Date.now() - 1000 * 60 * 60 * 24 * 9,
    totalFine: 300,
    amountPaid: 150,
    fineStatus: "partial",
    lockerId: "L-C310",
    description: "Locker being used by unauthorized student, policy violation",
    reportedBy: "Anna Lim",
    resolutionNotes:
      "Student agreed to payment plan, remaining balance due next week",
  },
  {
    id: "v-2024-004",
    studentId: "2023-78901",
    studentName: "Sofia Mendoza",
    violations: "Late Renewal",
    violationType: "late_renewal",
    dateOfInspection: Date.now() - 1000 * 60 * 60 * 24 * 5,
    dateReported: Date.now() - 1000 * 60 * 60 * 24 * 5,
    totalFine: 100,
    fineStatus: "waived",
    lockerId: "L-D415",
    description: "Failed to renew locker rental on time",
    reportedBy: "Carlos Santos",
    resolutionNotes: "Fine waived due to documented medical emergency",
  },
  {
    id: "v-2024-005",
    studentId: "2023-89012",
    studentName: "Antonio Villanueva",
    violations: "Prohibited Items",
    violationType: "prohibited_items",
    dateOfInspection: Date.now() - 1000 * 60 * 60 * 24 * 2,
    dateReported: Date.now() - 1000 * 60 * 60 * 24 * 2,
    totalFine: 400,
    fineStatus: "under_review",
    lockerId: "L-E520",
    description:
      "Found prohibited food items in locker causing odor, violation of policy",
    reportedBy: "Diana Ramos",
    evidence: ["img-prohibited-001.jpg"],
  },
]
